
// This file is generated by src/Tools/generateTemplates/templateClassPyExport.py out of the XML file
// Every change you make here gets lost in the next full rebuild!
#ifndef TECHDRAW_DRAWPAGEPY_H
#define TECHDRAW_DRAWPAGEPY_H

#include <App/DocumentObjectPy.h>
#include <Mod/TechDraw/App/DrawPage.h>
#include <string>


namespace TechDraw
{

//===========================================================================
// DrawPagePy - Python wrapper
//===========================================================================

/** The python export class for DrawPage
 */
class TechDrawExport DrawPagePy : public App::DocumentObjectPy
{
protected:
    ~DrawPagePy();

public:
    static PyTypeObject   Type;
    static PyMethodDef    Methods[];
    static PyGetSetDef    GetterSetter[];
    virtual PyTypeObject *GetType() {return &Type;}

public:
    DrawPagePy(DrawPage *pcObject, PyTypeObject *T = &Type);
    static PyObject *PyMake(struct _typeobject *, PyObject *, PyObject *);
    virtual int PyInit(PyObject* args, PyObject*k);


    using PointerType = DrawPage*;

    virtual PyObject *_repr();        // the representation
    std::string representation() const;

    /** @name callbacks and implementers for the python object methods */
    //@{
    /// callback for the addView() method
    static PyObject * staticCallback_addView (PyObject *self, PyObject *args);
    /// implementer for the addView() method
    PyObject*  addView(PyObject *args);
    /// callback for the removeView() method
    static PyObject * staticCallback_removeView (PyObject *self, PyObject *args);
    /// implementer for the removeView() method
    PyObject*  removeView(PyObject *args);
    /// callback for the getAllViews() method
    static PyObject * staticCallback_getAllViews (PyObject *self, PyObject *args);
    /// implementer for the getAllViews() method
    PyObject*  getAllViews(PyObject *args);
    /// callback for the requestPaint() method
    static PyObject * staticCallback_requestPaint (PyObject *self, PyObject *args);
    /// implementer for the requestPaint() method
    PyObject*  requestPaint(PyObject *args);
    //@}


    /** @name callbacks and implementers for the python object attributes */
    //@{
    ///getter callback for the PageWidth attribute
    static PyObject * staticCallback_getPageWidth (PyObject *self, void *closure);
    /// getter for the PageWidth attribute
    Py::Float getPageWidth() const;
    /// setter callback for the PageWidth attribute
    static int staticCallback_setPageWidth (PyObject *self, PyObject *value, void *closure);
    // no setter method,  PageWidth is read only!
    ///getter callback for the PageHeight attribute
    static PyObject * staticCallback_getPageHeight (PyObject *self, void *closure);
    /// getter for the PageHeight attribute
    Py::Float getPageHeight() const;
    /// setter callback for the PageHeight attribute
    static int staticCallback_setPageHeight (PyObject *self, PyObject *value, void *closure);
    // no setter method,  PageHeight is read only!
    ///getter callback for the PageOrientation attribute
    static PyObject * staticCallback_getPageOrientation (PyObject *self, void *closure);
    /// getter for the PageOrientation attribute
    Py::String getPageOrientation() const;
    /// setter callback for the PageOrientation attribute
    static int staticCallback_setPageOrientation (PyObject *self, PyObject *value, void *closure);
    // no setter method,  PageOrientation is read only!
    //@}

    /// getter method for special attributes (e.g. dynamic ones)
    PyObject *getCustomAttributes(const char* attr) const;
    /// setter for special attributes (e.g. dynamic ones)
    /// Output: Success=1, Failure=-1, Ignore=0
    int setCustomAttributes(const char* attr, PyObject *obj);
    PyObject *_getattr(const char *attr);              // __getattr__ function
    int _setattr(const char *attr, PyObject *value);        // __setattr__ function

    /// getter for the object handled by this class
    DrawPage *getDrawPagePtr() const;

};

}  //namespace TechDraw

#endif  // TECHDRAW_DRAWPAGEPY_H


