
// This file is generated by src/Tools/generateTemplates/templateClassPyExport.py out of the XML file
// Every change you make here gets lost in the next full rebuild!
#ifndef APP_GEOFEATUREPY_H
#define APP_GEOFEATUREPY_H

#include <App/DocumentObjectPy.h>
#include <App/GeoFeature.h>
#include <string>


namespace App
{

//===========================================================================
// GeoFeaturePy - Python wrapper
//===========================================================================

/** The python export class for GeoFeature
 */
class AppExport GeoFeaturePy : public App::DocumentObjectPy
{
protected:
    ~GeoFeaturePy();

public:
    static PyTypeObject   Type;
    static PyMethodDef    Methods[];
    static PyGetSetDef    GetterSetter[];
    virtual PyTypeObject *GetType() {return &Type;}

public:
    GeoFeaturePy(GeoFeature *pcObject, PyTypeObject *T = &Type);
    static PyObject *PyMake(struct _typeobject *, PyObject *, PyObject *);
    virtual int PyInit(PyObject* args, PyObject*k);


    using PointerType = GeoFeature*;

    virtual PyObject *_repr();        // the representation
    std::string representation() const;

    /** @name callbacks and implementers for the python object methods */
    //@{
    /// callback for the getPaths() method
    static PyObject * staticCallback_getPaths (PyObject *self, PyObject *args);
    /// implementer for the getPaths() method
    PyObject*  getPaths(PyObject *args);
    /// callback for the getGlobalPlacement() method
    static PyObject * staticCallback_getGlobalPlacement (PyObject *self, PyObject *args);
    /// implementer for the getGlobalPlacement() method
    PyObject*  getGlobalPlacement(PyObject *args);
    /// callback for the getPropertyNameOfGeometry() method
    static PyObject * staticCallback_getPropertyNameOfGeometry (PyObject *self, PyObject *args);
    /// implementer for the getPropertyNameOfGeometry() method
    PyObject*  getPropertyNameOfGeometry(PyObject *args);
    /// callback for the getPropertyOfGeometry() method
    static PyObject * staticCallback_getPropertyOfGeometry (PyObject *self, PyObject *args);
    /// implementer for the getPropertyOfGeometry() method
    PyObject*  getPropertyOfGeometry(PyObject *args);
    //@}


    /** @name callbacks and implementers for the python object attributes */
    //@{
    //@}

    /// getter method for special attributes (e.g. dynamic ones)
    PyObject *getCustomAttributes(const char* attr) const;
    /// setter for special attributes (e.g. dynamic ones)
    /// Output: Success=1, Failure=-1, Ignore=0
    int setCustomAttributes(const char* attr, PyObject *obj);
    PyObject *_getattr(const char *attr);              // __getattr__ function
    int _setattr(const char *attr, PyObject *value);        // __setattr__ function

    /// getter for the object handled by this class
    GeoFeature *getGeoFeaturePtr() const;

};

}  //namespace App

#endif  // APP_GEOFEATUREPY_H


