
// This file is generated by src/Tools/generateTemplates/templateClassPyExport.py out of the XML file
// Every change you make here gets lost in the next full rebuild!
#ifndef SPREADSHEET_PROPERTYCOLUMNWIDTHSPY_H
#define SPREADSHEET_PROPERTYCOLUMNWIDTHSPY_H

#include <Base/PersistencePy.h>
#include <Mod/Spreadsheet/App/PropertyColumnWidths.h>
#include <string>


namespace Spreadsheet
{

//===========================================================================
// PropertyColumnWidthsPy - Python wrapper
//===========================================================================

/** The python export class for PropertyColumnWidths
 */
class SpreadsheetExport PropertyColumnWidthsPy : public Base::PersistencePy
{
protected:
    ~PropertyColumnWidthsPy();

public:
    static PyTypeObject   Type;
    static PyMethodDef    Methods[];
    static PyGetSetDef    GetterSetter[];
    virtual PyTypeObject *GetType() {return &Type;}

public:
    PropertyColumnWidthsPy(PropertyColumnWidths *pcObject, PyTypeObject *T = &Type);
    static PyObject *PyMake(struct _typeobject *, PyObject *, PyObject *);
    virtual int PyInit(PyObject* args, PyObject*k);


    using PointerType = PropertyColumnWidths*;

    virtual PyObject *_repr();        // the representation
    std::string representation() const;

    /** @name callbacks and implementers for the python object methods */
    //@{
    //@}


    /** @name callbacks and implementers for the python object attributes */
    //@{
    //@}

    /// getter method for special attributes (e.g. dynamic ones)
    PyObject *getCustomAttributes(const char* attr) const;
    /// setter for special attributes (e.g. dynamic ones)
    /// Output: Success=1, Failure=-1, Ignore=0
    int setCustomAttributes(const char* attr, PyObject *obj);
    PyObject *_getattr(const char *attr);              // __getattr__ function
    int _setattr(const char *attr, PyObject *value);        // __setattr__ function

    /// getter for the object handled by this class
    PropertyColumnWidths *getPropertyColumnWidthsPtr() const;

};

}  //namespace Spreadsheet

#endif  // SPREADSHEET_PROPERTYCOLUMNWIDTHSPY_H


